import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/lib/Providers/QueryProvider";
import { ThemeProvider } from "@/lib/Providers/theme-provider";
import TopBar from "@/components/TopBar";
import { TaskStoreProvider } from "@/lib/Providers/task-store-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className` + `text-black`}>
        <TaskStoreProvider>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="w-full flex flex-col h-screen">
                <TopBar />
                {children}
              </main>
            </ThemeProvider>
          </QueryProvider>
        </TaskStoreProvider>
      </body>
    </html>
  );
}
